name: Deploy Rails App

on:
  push:
    branches:
      - main # Ou qualquer outro nome de branch que você utiliza para deploy
    paths:
      - '**/*.rb'  # Rastreia alterações nos arquivos Ruby

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: myapp_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-timeout=30s --health-start-period=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Set up database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create db:schema:load RAILS_ENV=test

      - name: Run tests
        run: |
          bundle exec rspec

  deploy:
    runs-on: ubuntu-latest
    needs: test  # O deploy só será feito se o teste for bem-sucedido

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'  # Defina a versão do Ruby que você usa na sua aplicação

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Deploy to EC2
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          EC2_USER: ubuntu  # Usuário padrão no Ubuntu EC2
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no -i $EC2_PRIVATE_KEY $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/your-rails-app
            git pull origin main
            bundle install
            rake db:migrate RAILS_ENV=production
            bundle exec puma -e production -d
          EOF
